// Generated by scripts/sync_version.ps1 from pubspec.yaml. Do not edit.
class AppVersion {
  static const String name = '1.0.0';
  static const int build = 1;
  static const String full = '1.0.0+1';
}
