#requires -Version 7.0
param([switch]$Check)
. (Join-Path $PSScriptRoot 'release_common.ps1')
$root = Get-ReleaseRoot
$version = Get-ReleaseVersion $root
$path = Join-Path $root 'lib/core/app_version.dart'
$expected = @"
// Generated by scripts/sync_version.ps1 from pubspec.yaml. Do not edit.
class AppVersion {
  static const String name = '$($version.Version)';
  static const int build = $($version.Build);
  static const String full = '$($version.Full)';
}
"@ + "`n"
if ($Check) {
    if (!(Test-Path -LiteralPath $path) -or
        [IO.File]::ReadAllText($path).Replace("`r`n", "`n") -ne $expected.Replace("`r`n", "`n")) {
        throw 'Version desincronizada. Ejecuta scripts/sync_version.ps1.'
    }
} else {
    Write-ReleaseText $path $expected
}
Write-Host "Version sincronizada: $($version.Full)"
